# Generated by Django 4.1.6 on 2023-02-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stage_ticket_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='createdAt',
        ),
    ]
