# Generated by Django 4.1.6 on 2023-02-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stage_ticket_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
            preserve_default=False,
        ),
    ]
