# Generated by Django 4.1.6 on 2023-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_ticket_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
