# Generated by Django 4.1.6 on 2023-02-11 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stage',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
